### ISSUE TITLE
merging stalin-sort repos

### ISSUE THREAD

**Issue by gustavo-depaula** [MeilCli/StalinSort#1]
what do you think of merging our stalin-sort repos?
i'd love to see your Crystal resolution in https://github.com/gustavo-depaula/stalin-sort !

best regards,

**Comment by MeilCli** [comment]
@gustavo-depaula 
i think good idea, but i am afraid that your repository is not licensed.
Do you have idea to attach [OSS License](https://opensource.org/licenses)?

**Comment by gustavo-depaula** [comment]
we now have!! https://github.com/gustavo-depaula/stalin-sort/pull/72

**Comment by MeilCli** [comment]
@gustavo-depaula 
thanks!
i just made PR that merge same crystal code.

**Comment by gustavo-depaula** [comment]
I'm closing this issue, thanks for your contribution! <3
